In [4]:
import torch
from torch.utils.data import Dataset, DataLoader
from src.PreProc_Data.DataProc import StackedSequenceDataset
import numpy as np
from src.MZA_Experiment import MZA_Experiment
import sys
# from MZA_Experiment import MZA_Experiment

In [5]:
if torch.cuda.is_available():
    device = torch.device("cuda")
elif torch.backends.mps.is_available():
    device = torch.device("mps") 
else:
    device = torch.device("cpu")

In [6]:
model = torch.load("Trained_Models/sl33_nhu40_numobs4_bs256_lr5e-5_ph20")

In [19]:
total_memory_usage = 0
for name, parameter in model.named_parameters():
    memory_usage = parameter.element_size() * parameter.nelement()  # in bytes
    total_memory_usage += memory_usage
    print(f"{name}: {memory_usage/(1024 ** 3)} gb")

print(f"Total memory usage of the model: {total_memory_usage/(1024 ** 3)} gb")






autoencoder.e_fc1.weight: 0.000244140625 gb
autoencoder.e_fc1.bias: 1.9073486328125e-06 gb
autoencoder.e_fc2.weight: 0.00048828125 gb
autoencoder.e_fc2.bias: 9.5367431640625e-07 gb
autoencoder.e_fc3.weight: 0.0001220703125 gb
autoencoder.e_fc3.bias: 4.76837158203125e-07 gb
autoencoder.e_fc4.weight: 3.0517578125e-05 gb
autoencoder.e_fc4.bias: 2.384185791015625e-07 gb
autoencoder.e_fc5.weight: 9.5367431640625e-07 gb
autoencoder.e_fc5.bias: 1.4901161193847656e-08 gb
autoencoder.d_fc1.weight: 9.5367431640625e-07 gb
autoencoder.d_fc1.bias: 2.384185791015625e-07 gb
autoencoder.d_fc2.weight: 3.0517578125e-05 gb
autoencoder.d_fc2.bias: 4.76837158203125e-07 gb
autoencoder.d_fc3.weight: 0.0001220703125 gb
autoencoder.d_fc3.bias: 9.5367431640625e-07 gb
autoencoder.d_fc4.weight: 0.00048828125 gb
autoencoder.d_fc4.bias: 1.9073486328125e-06 gb
autoencoder.d_fc5.weight: 0.000244140625 gb
autoencoder.d_fc5.bias: 4.76837158203125e-07 gb
koopman.kMatrix: 5.960464477539063e-08 gb
seqmodel.lstm.weight_ih_

In [16]:
model.autoencoder.e_fc1.weight

Parameter containing:
tensor([[-0.0701,  0.0831,  0.0792,  ..., -0.0073,  0.0095,  0.0385],
        [ 0.0839,  0.0840,  0.0140,  ...,  0.0113,  0.0493, -0.0292],
        [-0.0775,  0.0214, -0.0421,  ..., -0.0860,  0.0544, -0.0727],
        ...,
        [-0.0553,  0.0849,  0.0134,  ..., -0.0295,  0.0536,  0.0060],
        [-0.0299,  0.0686,  0.0190,  ..., -0.0460, -0.0296, -0.0312],
        [-0.0235,  0.0051,  0.0161,  ...,  0.0543, -0.0046,  0.0532]],
       device='cuda:0', requires_grad=True)

In [20]:
import pickle

with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

In [21]:
scripted_model = torch.jit.script(model)

# Save the TorchScript model
scripted_model.save('scripted_model.pt')

TypeError: module, class, method, function, traceback, frame, or code object was expected, got builtin_function_or_method

In [11]:
total = 0
for element_name in dir(model):
    element = getattr(model, element_name)
    element_size = sys.getsizeof(element)
    total += element_size
    print(f"Element: {element_name}, Size: {element_size} bytes")

print(total)
print(sys.getsizeof(model))

Element: T_destination, Size: 88 bytes
Element: __annotations__, Size: 360 bytes
Element: __call__, Size: 64 bytes
Element: __class__, Size: 1064 bytes
Element: __delattr__, Size: 64 bytes
Element: __dict__, Size: 640 bytes
Element: __dir__, Size: 64 bytes
Element: __doc__, Size: 16 bytes
Element: __eq__, Size: 48 bytes
Element: __format__, Size: 72 bytes
Element: __ge__, Size: 48 bytes
Element: __getattr__, Size: 64 bytes
Element: __getattribute__, Size: 48 bytes
Element: __gt__, Size: 48 bytes
Element: __hash__, Size: 48 bytes
Element: __init__, Size: 64 bytes
Element: __init_subclass__, Size: 72 bytes
Element: __le__, Size: 48 bytes
Element: __lt__, Size: 48 bytes
Element: __module__, Size: 70 bytes
Element: __ne__, Size: 48 bytes
Element: __new__, Size: 72 bytes
Element: __reduce__, Size: 72 bytes
Element: __reduce_ex__, Size: 72 bytes
Element: __repr__, Size: 64 bytes
Element: __setattr__, Size: 64 bytes
Element: __setstate__, Size: 64 bytes
Element: __sizeof__, Size: 72 bytes
Ele

In [22]:
checkpoint = model

# Print the keys in the checkpoint dictionary
print("Keys in the checkpoint:")
for key in checkpoint.keys():
    print(key)

Keys in the checkpoint:


AttributeError: 'MZANetwork' object has no attribute 'keys'

In [3]:
tensor = torch.tensor([
    [0, 0, 0, 0],
    [1, 2, 3, 4],
    [0, 0, 0, 0],
    [0, 1, 0, 1]
])

# Check if all elements in each row are zero
all_zeros_rows = torch.all(tensor == 0, dim=1)

# Print the result
print("Rows containing all zeros:", all_zeros_rows)







Rows containing all zeros: tensor([ True, False,  True, False])


In [16]:
tensor = torch.tensor([
    [[0, 0],
     [0, 0]],

    [[1, 2],
     [0, 0]],

    [[0, 0],
     [0, 0]]
])

t = tensor
for i in range(tensor.ndim-1):
    if i == 0:
        t = torch.all(t == 0, dim = -1)
    else:
        t = torch.all(t == True, dim = -1)
~t 

tensor[~t]

tensor([[[1, 2],
         [0, 0]]])

In [12]:
torch.all(tensor == 0, dim = -1)

tensor([[ True,  True],
        [False,  True],
        [ True,  True]])

In [3]:
data = np.load("Data/2DCylinder/processed_data/npyfiles/nektar_cyl_data_20_dt0.25_T200.npy")
# data = data[:,:,:2]
# data = np.einsum('ijk->jki',data)
data.shape


(1, 801, 7938)

In [5]:
args_dict = {"device": device, "seq_len": 5, "pred_horizon": 5}
dataset   = StackedSequenceDataset(data, args_dict)
it = iter(dataset)
Phi_seq, Phi_nn = next(it)
print("Phi_seq shape:", Phi_seq.shape)
print("Phi_seq shpae:", Phi_nn.shape)
print(len(dataset))

0  data1:  torch.Size([1, 5, 7938])
1  data1:  torch.Size([1, 5, 7938])
2  data1:  torch.Size([1, 5, 7938])
3  data1:  torch.Size([1, 5, 7938])
4  data1:  torch.Size([1, 5, 7938])
5  data1:  torch.Size([1, 5, 7938])
6  data1:  torch.Size([1, 5, 7938])
7  data1:  torch.Size([1, 5, 7938])
8  data1:  torch.Size([1, 5, 7938])
9  data1:  torch.Size([1, 5, 7938])
10  data1:  torch.Size([1, 5, 7938])
11  data1:  torch.Size([1, 5, 7938])
12  data1:  torch.Size([1, 5, 7938])
13  data1:  torch.Size([1, 5, 7938])
14  data1:  torch.Size([1, 5, 7938])
15  data1:  torch.Size([1, 5, 7938])
16  data1:  torch.Size([1, 5, 7938])
17  data1:  torch.Size([1, 5, 7938])
18  data1:  torch.Size([1, 5, 7938])
19  data1:  torch.Size([1, 5, 7938])
20  data1:  torch.Size([1, 5, 7938])
21  data1:  torch.Size([1, 5, 7938])
22  data1:  torch.Size([1, 5, 7938])
23  data1:  torch.Size([1, 5, 7938])
24  data1:  torch.Size([1, 5, 7938])
25  data1:  torch.Size([1, 5, 7938])
26  data1:  torch.Size([1, 5, 7938])
27  data1: 

: 

In [ ]:
seqdataset = SequenceDataset(data, device)
# dataloader = DataLoader(dataset, batch_size = 16, shuffle =True)

In [ ]:
it = iter(seqdataset)
Phi_seq, Phi_nn = next(it)
for i, data in enumerate(seqdataset):
    if (i!=0):
        Phi_seq = torch.cat((Phi_seq, data[0]), dim = 0)
        Phi_nn  = torch.cat((Phi_nn, data[1]), dim = 0)
print(Phi_seq.shape)
print(Phi_nn.shape)
   


In [ ]:
dataloader = DataLoader(dataset, batch_size = 16, shuffle =True)

it = iter(dataloader)
Phi_seq, Phi_nn = next(it)
print(Phi_seq.shape)
print(Phi_nn.shape)

In [ ]:
k = {"a":1,"b":2}
print(type(k))

In [ ]:
from Layers.Koopman import Koopman


In [ ]:
koopman = Koopman(5,device)
koopman.kMatrixUT.requires_grad 

In [ ]:
sum(p.numel() for p in koopman.parameters())

In [ ]:
for parameter in koopman.parameters():
    print(parameter)

In [ ]:
import random
import torch
import torch.nn as nn
from torch.autograd import Variable
from torch import optim
import torch.nn.functional as F

seq_len = 10
n_class = 5
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.W = nn.Parameter(torch.randn(seq_len, n_class), requires_grad=True)
        
    def forward(self, x):
        x = torch.matmul(x, self.W)
        x = F.relu(x)
        x = F.log_softmax(x)
        return x

model = SimpleNet()
print('parameters----------')
for parameter in model.parameters():
    print("hello")
    print(parameter)
    print("hello")

optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.0001)
loss_fn = nn.NLLLoss()
for i in range(10000):
    in_data = Variable(torch.FloatTensor([[random.randint(0, n_class-1) for _ in range(seq_len)]]))
    target_data = Variable(torch.LongTensor([ int(in_data.data[0][0]) ]))
    
    optimizer.zero_grad()
    output = model(in_data)
    loss = loss_fn(output, target_data)
    loss.backward()
    optimizer.step()
    if i % 1000 == 0:
        print('loss:', loss.data[0])
    
# test
print('======Test======')
for i in range(10):
    in_data = Variable(torch.FloatTensor([[random.randint(0, n_class-1) for _ in range(seq_len)]]))
    target_data = int(in_data.data[0][0])
    out = model(in_data)
    _, ind = torch.max(out.data[0], 0)
    print(ind[0] == target_data, 'out', ind[0], 'label', target_data)

print('after parameters')
print(next(model.parameters()))

In [ ]:
import numpy as np
data = np.load("Data/KS/ks_N256_dt0.001_L6.npy")
data = data[:15,::100,:]
data.shape

In [ ]:
np.save("Data/KS/ks_N256_dt0.001_L6_short.npy", data)

In [ ]:
a = [0,1,2,3,4,5,6,7]
print(a[5:])

import torch

b = torch.tensor(a)

tuple(b.shape)

In [15]:
b = torch.tensor([[1,2],[3,4]]).reshape(2,2)

a = torch.arange(1,9).reshape(2,2,2)

c = torch.einsum("bsh,bs->bh",[a,b])
print(a.shape,b.shape,c.shape)
a,b,c

torch.Size([2, 2, 2]) torch.Size([2, 2]) torch.Size([2, 2])


(tensor([[[1, 2],
          [3, 4]],
 
         [[5, 6],
          [7, 8]]]),
 tensor([[1, 2],
         [3, 4]]),
 tensor([[ 7, 10],
         [43, 50]]))